### PR TITLE
Some optimize

### PR DESCRIPTION
**Pull request by meiMingle**
Replace internal API;
Enable and disable plug-ins without restarting;
Compatible with 2023.*

### CODE REVIEW

**Comment by xiaozhuai** [comment]
Hello @meiMingle , thanks for the PR.
BTW, if I understand correct, we can remove `require-restart="true"` in the `plugin.xml`, isn't it?

**Comment by meiMingle** [comment]
> Hello @meiMingle , thanks for the PR. BTW, if I understand correct, we can remove `require-restart="true"` in the `plugin.xml`, isn't it?

Yeah I just forgot to remove it, I just fixed it

**Comment by xiaozhuai** [comment]
@meiMingle Thanks again! Merged.

**Comment by xiaozhuai** [comment]
Will release 1.1.4 soon.

**Comment by meiMingle** [comment]
> @meiMingle Thanks again! Merged.

I'm also grateful to you. I created another plug-in that supports viewing JPEGXL format files based on my study of your code. [JPEGXL Support](https://plugins.jetbrains.com/plugin/22925-jpegxl-support)

**Pull request merged**
